# Generated by Django 5.2.17 on 2026-09-28 14:23

import clinic.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "health_id",
                    models.CharField(
                        default=clinic.models.health_id,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "card_locator",
                    models.CharField(
                        default=clinic.models.card_locator,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("blood_group", models.CharField(default="unknown", max_length=8)),
                ("emergency_contact", models.CharField(blank=True, max_length=250)),
                ("allergy_status", models.CharField(default="unknown", max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("complaint", models.CharField(max_length=1000)),
                ("diagnosis", models.CharField(blank=True, max_length=1000)),
                ("notes", models.TextField(blank=True)),
                ("vitals", models.JSONField(default=dict)),
                ("correction_reason", models.CharField(blank=True, max_length=1000)),
                (
                    "correction_of",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic.medicalrecord",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clinic.patient"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClinicalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                ("notes", models.CharField(blank=True, max_length=1000)),
                ("source", models.CharField(max_length=20)),
                ("resolved_at", models.DateTimeField(null=True)),
                ("resolution_reason", models.CharField(blank=True, max_length=1000)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clinic.patient"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.CharField(max_length=80)),
                ("outcome", models.CharField(default="success", max_length=20)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField()),
                ("notes", models.CharField(blank=True, max_length=2000)),
                ("cancelled_at", models.DateTimeField(null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=1000)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clinic.patient"
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic.medicalrecord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DispenseEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.CharField(max_length=100)),
                ("payload_digest", models.CharField(max_length=64)),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_health_id", models.CharField(max_length=32)),
                ("pharmacist_name", models.CharField(max_length=200)),
                ("shop_name", models.CharField(max_length=180)),
                (
                    "pharmacist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispensing",
                        to="clinic.prescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("medicine", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=250)),
                ("instructions", models.CharField(blank=True, max_length=1000)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(max_length=40)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="clinic.prescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DispenseItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(max_length=40)),
                ("medicine", models.CharField(max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="clinic.dispenseevent",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispenses",
                        to="clinic.prescriptionitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("registration_number", models.CharField(max_length=100)),
                ("registering_body", models.CharField(max_length=150)),
                ("specialty", models.CharField(blank=True, max_length=150)),
                ("practice_address", models.CharField(max_length=500)),
                ("shop_name", models.CharField(blank=True, max_length=180)),
                ("shop_license", models.CharField(blank=True, max_length=100)),
                ("shop_license_expires", models.DateField(blank=True, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("reason", models.CharField(blank=True, max_length=1000)),
                ("evidence_reviewed", models.CharField(blank=True, max_length=1000)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prescription",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="clinic.providerapplication",
            ),
        ),
        migrations.AddField(
            model_name="dispenseevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="clinic.providerapplication",
            ),
        ),
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scope", models.CharField(max_length=12)),
                ("purpose", models.CharField(max_length=300)),
                ("status", models.CharField(default="pending", max_length=12)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clinic.patient"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic.providerapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scope", models.CharField(max_length=12)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic.accessrequest",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clinic.patient"
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic.prescription",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic.providerapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=180)),
                ("storage_name", models.CharField(max_length=100, unique=True)),
                ("content_type", models.CharField(max_length=40)),
                ("status", models.CharField(default="quarantined", max_length=15)),
                ("reviewed_at", models.DateTimeField(null=True)),
                ("review_reason", models.CharField(blank=True, max_length=1000)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="clinic.providerapplication",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decision", models.CharField(max_length=12)),
                ("reason", models.CharField(max_length=1000)),
                ("evidence_reviewed", models.CharField(blank=True, max_length=1000)),
                ("valid_until", models.DateTimeField(null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="clinic.providerapplication",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0"))),
                name="prescribed_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispenseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0"))),
                name="dispensed_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispenseitem",
            constraint=models.UniqueConstraint(
                fields=("event", "prescription_item"), name="dispense_item_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerapplication",
            constraint=models.UniqueConstraint(
                fields=("provider", "version"), name="provider_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("provider",),
                name="provider_current_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("status", "approved")),
                fields=("registering_body", "registration_number"),
                name="approved_credential_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current", True),
                    ("status", "approved"),
                    models.Q(("shop_license", ""), _negated=True),
                ),
                fields=("registering_body", "shop_license"),
                name="approved_shop_license_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispenseevent",
            constraint=models.UniqueConstraint(
                fields=("pharmacist", "idempotency_key"),
                name="pharmacist_idempotency_unique",
            ),
        ),
    ]
