# Generated by Django 5.2.17 on 2026-09-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providerapplication",
            name="clinic_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="providerapplication",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="providerapplication",
            name="qualification",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="providerapplication",
            name="years_experience",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerdocument",
            name="kind",
            field=models.CharField(
                choices=[("credential", "Credential evidence"), ("photo", "Photo")],
                default="credential",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="providerdocument",
            name="size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
