# Generated by Django 5.2.17 on 2026-09-28 18:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_patients(apps, schema_editor):
    """Keep each doctor's existing encounter/prescription patients in My patients."""
    using = schema_editor.connection.alias
    SavedPatient = apps.get_model("clinic", "DoctorPatient")
    records = apps.get_model("clinic", "MedicalRecord").objects.using(using)
    prescriptions = apps.get_model("clinic", "Prescription").objects.using(using)
    pairs = (
        records.order_by()
        .values_list("doctor_id", "patient_id")
        .union(prescriptions.order_by().values_list("doctor_id", "patient_id"))
    )
    batch = []
    for doctor_id, patient_id in pairs.iterator(chunk_size=1000):
        batch.append(SavedPatient(doctor_id=doctor_id, patient_id=patient_id))
        if len(batch) == 1000:
            SavedPatient.objects.using(using).bulk_create(batch, ignore_conflicts=True)
            batch = []
    if batch:
        SavedPatient.objects.using(using).bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0003_patient_photo_content_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPatient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_by_doctors",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["doctor", "-created_at", "id"],
                        name="doctor_saved_patient_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "patient"), name="doctor_patient_unique"
                    )
                ],
            },
        ),
        migrations.RunPython(preserve_existing_patients, migrations.RunPython.noop),
    ]
