# Generated by Django 5.2.17 on 2026-09-29 14:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0004_doctor_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120)),
                ("value", models.DecimalField(decimal_places=5, max_digits=16)),
                ("unit", models.CharField(max_length=40)),
                (
                    "reference_low",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=16, null=True
                    ),
                ),
                (
                    "reference_high",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=16, null=True
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_results",
                        to="clinic.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_results",
                        to="clinic.medicalreport",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["patient", "-measured_at"],
                        name="patient_lab_measured_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reference_low__isnull", True),
                            ("reference_high__isnull", True),
                            ("reference_low__lte", models.F("reference_high")),
                            _connector="OR",
                        ),
                        name="lab_reference_range_ordered",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationAdherenceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("scheduled_doses", models.PositiveIntegerField()),
                ("taken_doses", models.PositiveIntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adherence_logs",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["patient", "-date"], name="patient_adherence_date_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "date"), name="patient_adherence_day_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scheduled_doses__gt", 0)),
                        name="adherence_scheduled_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("taken_doses__lte", models.F("scheduled_doses"))
                        ),
                        name="adherence_taken_within_schedule",
                    ),
                ],
            },
        ),
    ]
