# Generated by Django 5.2.17 on 2026-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_patient_health_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='extraction',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
