# Generated by Django 5.2.17 on 2026-09-30 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_report_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadherencelog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adherence_logs', to='clinic.medicalreport'),
        ),
    ]
