"use client";
import { useRef, useState } from "react";
import { ArrowLeft, Download, FileText, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { api, date, dateTime, list, post, values } from "@/lib/api";
import type { Audit, ClinicalRecord, Dispensing, Entry, Prescription, User } from "@/lib/types";
import { AsyncForm, Badge, Empty, Field, Panel, QueryState, Refresh, Select, Textarea, useQuery } from "./ui";

export function Pagination({ page, setPage, length }: {page: number; setPage: (page: number) => void; length: number}) {
  if (page === 1 && length < 50) return null;
  return <div className="inline-actions section-gap"><button className="button secondary small" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span className="muted">Page {page}</span><button className="button secondary small" disabled={length < 50} onClick={() => setPage(page + 1)}>Next</button></div>;
}
export function Entries({ patientId, kind, user, canAdd = true }: {patientId: string; kind: "allergies" | "conditions"; user?: User; canAdd?: boolean}) {
  const query = useQuery<{results: Entry[]}>(`/patients/${patientId}/${kind}/`); const entries = list(query.data); const [adding, setAdding] = useState(false);
  return <Panel title={kind === "allergies" ? "Allergies" : "Chronic conditions"} action={canAdd && <button className="button quiet small" onClick={() => setAdding(!adding)}><Plus size={15}/>{adding ? "Close" : "Add"}</button>}><QueryState query={query}>{!entries.length ? <p className="muted" style={{fontSize:12}}>No {kind === "allergies" ? "allergy entries" : "chronic conditions"} recorded. No entries does not mean none are known.</p> : entries.map(entry => <div className="list-row" key={entry.id}><div className="row-content"><h3>{entry.name} {entry.resolved_at && <Badge>resolved</Badge>}</h3>{entry.notes && <p>{entry.notes}</p>}<p className="row-meta">{entry.source.replaceAll("_"," ")} · {entry.author_name} · {date(entry.created_at)}</p></div>{!entry.resolved_at && user?.id === entry.author_id && <details><summary className="text-button">Resolve</summary><AsyncForm submit="Confirm resolution" successText="" onSubmit={async form => { await post(`/patients/${patientId}/${kind}/${entry.id}/resolve/`, values(form)); query.reload(); }}><Field name="reason" label="Reason (own entries only)" required/></AsyncForm></details>}</div>)}</QueryState>{adding && <div className="section-gap"><AsyncForm submit="Add entry" successText="" onSubmit={async form => { await post(`/patients/${patientId}/${kind}/`, values(form)); setAdding(false); query.reload(); }}><Field label={kind === "allergies" ? "Allergen" : "Condition"} name="name" required maxLength={200}/><Textarea label="Notes" name="notes"/></AsyncForm></div>}</Panel>;
}
export function Records({ path, patientId, user, showHeading = true }: {path: string; patientId?: string; user?: User; showHeading?: boolean}) {
  const [page, setPage] = useState(1); const query = useQuery<{results: ClinicalRecord[]}>(`${path}?page=${page}`); const records = list(query.data);
  const [adding, setAdding] = useState(false); const [correction, setCorrection] = useState<ClinicalRecord>();
  return <Panel title={showHeading ? "Consultations & medical records" : undefined} action={<div className="inline-actions"><Refresh onClick={query.reload}/>{patientId && <button className="button secondary small" onClick={() => { setAdding(!adding); setCorrection(undefined); }}><Plus size={14}/>Add consultation</button>}</div>}>
    {(adding || correction) && <div className="section-gap" style={{marginBottom:24}}><h3>{correction ? "Add a linked correction" : "New consultation"}</h3><p className="progress-note">Finalized records cannot be edited. A correction adds a new linked record and preserves the original author, content, and timestamp.</p><AsyncForm submit={correction ? "Save correction" : "Finalize consultation"} successText="" onSubmit={async form => { const data = values(form); await post(correction ? `/records/${correction.id}/corrections/` : `/patients/${patientId}/records/`, {complaint:data.complaint, diagnosis:data.diagnosis, notes:data.notes, correction_reason:data.correction_reason, vitals:Object.fromEntries(["blood_pressure","pulse","temperature","weight","glucose_mg_dl","glucose_context"].filter(key => data[key]).map(key => [key,data[key]]))}); setAdding(false); setCorrection(undefined); query.reload(); }}><Field label="Presenting complaint" name="complaint" required defaultValue={correction?.complaint}/><Field label="Diagnosis" name="diagnosis" defaultValue={correction?.diagnosis}/><Textarea label="Consultation notes" name="notes" defaultValue={correction?.notes}/><div className="form-grid"><Field label="Blood pressure (mmHg)" name="blood_pressure" placeholder="e.g. 120/80" defaultValue={correction?.vitals.blood_pressure}/><Field label="Pulse (beats/minute)" name="pulse" defaultValue={correction?.vitals.pulse}/><Field label="Temperature (°C)" name="temperature" defaultValue={correction?.vitals.temperature}/><Field label="Weight (kg)" name="weight" defaultValue={correction?.vitals.weight}/><Field label="Blood sugar (mg/dL)" name="glucose_mg_dl" type="number" min="0.01" step="0.01" defaultValue={correction?.vitals.glucose_mg_dl}/><Select label="Blood sugar context" name="glucose_context" defaultValue={correction?.vitals.glucose_context || ""}><option value="">Not specified</option><option value="fasting">Fasting</option><option value="random">Random</option><option value="after_meal">After meal</option></Select></div>{correction && <Textarea label="Reason for correction" name="correction_reason" required/>}</AsyncForm><button className="text-button section-gap" onClick={() => { setAdding(false); setCorrection(undefined); }}>Cancel</button></div>}
    <p className="progress-note">Records from all treating doctors appear below. Earlier consultations remain read-only.</p><QueryState query={query}>{!records.length ? <Empty title="Your story starts with your next visit.">Consultations from approved doctors will appear here, with their original author and date.</Empty> : <div>{records.map(record => <article className="timeline-item" key={record.id}><time>{dateTime(record.created_at)}</time><h3>{record.complaint}</h3><p className="muted">Dr. {record.doctor_name}{record.doctor_account_id && ` · ${record.doctor_account_id}`}{record.correction_of && " · Linked correction"}</p><details><summary>View consultation</summary><div className="record-body"><div><strong>Symptoms / reason for visit</strong><p>{record.complaint}</p></div>{record.diagnosis && <div><strong>Diagnosis</strong><p>{record.diagnosis}</p></div>}{record.notes && <div><strong>Doctor’s examination and care plan</strong><p>{record.notes}</p></div>}{Object.keys(record.vitals || {}).length > 0 && <div><strong>Vitals</strong><p>{Object.entries(record.vitals).map(([key,value]) => `${key.replaceAll("_"," ")}: ${value}`).join(" · ")}</p></div>}{record.correction_reason && <div><strong>Correction reason</strong><p>{record.correction_reason}</p></div>}{record.correction_of && <p className="muted">Original record: {record.correction_of}</p>}{patientId && user?.id === record.doctor_id && <button className="text-button" onClick={() => { setCorrection(record); setAdding(false); }}>Add correction</button>}</div></details></article>)}</div>}</QueryState><Pagination page={page} setPage={setPage} length={records.length}/></Panel>;
}
export function PrescriptionDetail({ id, user, onBack }: {id: string; user: User; onBack: () => void}) {
  const query = useQuery<Prescription>(`/prescriptions/${id}/`); const prescription = query.data;
  const idempotency = useRef<{key: string; body: string} | null>(null);
  return <div><button className="page-back" onClick={onBack}><ArrowLeft size={15}/>Back to prescriptions</button><Panel title="Prescription" action={<Refresh onClick={query.reload}/>}><QueryState query={query}>{prescription && <><div className="detail-title"><div><h3>{prescription.patient.name}</h3><p>{prescription.patient.account_id || prescription.patient.health_id} · Issued {date(prescription.created_at)}</p><p>Dr. {prescription.doctor_name} · {prescription.doctor_registration}</p></div><Badge>{prescription.status}</Badge></div><dl className="detail-list section-gap"><div className="detail-item"><dt>Valid until</dt><dd>{dateTime(prescription.valid_until)}</dd></div><div className="detail-item"><dt>Prescription ID</dt><dd>{prescription.id}</dd></div></dl>{prescription.notes && <p className="wrap-text section-gap">{prescription.notes}</p>}{prescription.cancellation_reason && <div className="notice info section-gap">Cancellation reason: {prescription.cancellation_reason}</div>}<div className="table-wrap section-gap"><table><thead><tr><th>Medicine & instructions</th><th>Prescribed</th><th>Dispensed</th><th>Remaining</th></tr></thead><tbody>{prescription.items.map(item => <tr key={item.id}><td><strong>{item.medicine}</strong><small>{item.dosage}</small><small>{item.instructions}</small></td><td>{item.quantity} {item.unit}</td><td>{item.dispensed} {item.unit}</td><td>{item.remaining} {item.unit}</td></tr>)}</tbody></table></div><div className="section-gap"><a className="button secondary small" href={`/api/v1/prescriptions/${prescription.id}/pdf/`} target="_blank" rel="noreferrer"><Download size={15}/>Download prescription</a></div>{user.role === "pharmacist" && <div className="section-gap"><h3>Allergy information</h3><p className="section-gap">Status: <strong>{prescription.allergy_status === "none_known" ? "No known allergies" : prescription.allergy_status === "reported" ? "Known allergies reported" : "Unknown / not assessed"}</strong></p><p className="muted" style={{fontSize:12}}>Use the patient’s reported status and recorded entries; missing information does not mean no known allergies.</p>{(prescription.allergies || []).map(entry => <div className="list-row" key={entry.id}><div><h3>{entry.name}</h3><p>{entry.notes} · {entry.source} · {entry.author_name}</p></div></div>)}</div>}
    {user.role === "pharmacist" && ["issued","partially_dispensed"].includes(prescription.status) && <div className="section-gap"><h3>Record medicines handed over</h3><p className="progress-note">Enter only the quantity actually dispensed, in the exact prescribed unit. Leave other items at zero.</p><AsyncForm submit="Confirm dispensing" successText="Dispensing recorded." onSubmit={async form => { const data = values(form); const items = prescription.items.filter(item => Number(data[item.id]) > 0).map(item => ({prescription_item_id:item.id,quantity:data[item.id],unit:item.unit})); if (!items.length) throw new Error("Enter a positive quantity for at least one medicine."); const body = JSON.stringify({items}); if (!idempotency.current || idempotency.current.body !== body) idempotency.current = {key:crypto.randomUUID(),body}; await api(`/prescriptions/${id}/dispense/`,{method:"POST",headers:{"Idempotency-Key":idempotency.current.key},body}); idempotency.current = null; query.reload(); }}><div className="form-grid">{prescription.items.filter(item => Number(item.remaining)>0).map(item => <Field key={item.id} label={`${item.medicine} (${item.unit})`} name={item.id} type="number" step="0.001" min="0" max={item.remaining} defaultValue="0" hint={`${item.remaining} ${item.unit} remaining`}/>)}</div><label className="checkbox"><input type="checkbox" required/><span>I confirm these quantities have been handed over to this patient.</span></label></AsyncForm></div>}
    {user.role === "doctor" && user.id === prescription.doctor_id && !["cancelled","expired","fulfilled"].includes(prescription.status) && <details className="section-gap"><summary className="text-button">Cancel this prescription</summary><AsyncForm submit="Cancel prescription" successText="" onSubmit={async form => { await post(`/prescriptions/${id}/cancel/`,values(form)); query.reload(); }}><Textarea label="Reason for cancellation" name="reason" required/></AsyncForm></details>}</>}</QueryState></Panel></div>;
}
export function Prescriptions({ path, user, patientId, showHeading = true }: {path: string; user: User; patientId?: string; showHeading?: boolean}) {
  const consultations = useQuery<{results: ClinicalRecord[]}>(patientId && user.role === "doctor" ? `/patients/${patientId}/records/` : null);
  const [page, setPage] = useState(1); const query = useQuery<{results: Prescription[]}>(`${path}?page=${page}`); const prescriptions = list(query.data); const [selected, setSelected] = useState<string>(); const [adding, setAdding] = useState(false); const [items, setItems] = useState([crypto.randomUUID()]);
  if (selected) return <PrescriptionDetail id={selected} user={user} onBack={() => { setSelected(undefined); query.reload(); }}/>;
  return <Panel title={showHeading ? user.role === "pharmacist" ? "Patient prescriptions" : "Prescriptions" : undefined} action={<div className="inline-actions"><Refresh onClick={query.reload}/>{patientId && user.role === "doctor" && <button className="button secondary small" onClick={() => setAdding(!adding)}><Plus size={15}/>Write prescription</button>}</div>}>
  {adding && <div style={{marginBottom:24}}><p className="progress-note">Enter your clinical instructions. MedyLink does not generate dosage advice or check drug safety.</p><AsyncForm submit="Issue prescription" successText="" onSubmit={async form => { const data = values(form); await post(`/patients/${patientId}/prescriptions/`,{valid_until:new Date(data.valid_until).toISOString(),notes:data.notes,record_id:data.record_id || null,items:items.map(key => ({medicine:data[`medicine_${key}`],dosage:data[`dosage_${key}`],instructions:data[`instructions_${key}`],quantity:data[`quantity_${key}`],unit:data[`unit_${key}`]}))}); setAdding(false); setItems([crypto.randomUUID()]); query.reload(); }}><label className="field"><span>Consultation (optional)</span><select name="record_id" defaultValue=""><option value="">Standalone prescription</option>{list(consultations.data).filter(record => record.doctor_id === user.id).map(record => <option value={record.id} key={record.id}>{date(record.created_at)} · {record.complaint}</option>)}</select><small>Link this prescription to a visit in the patient’s history.</small></label><Field label="Valid until" name="valid_until" type="datetime-local" required min={new Date().toISOString().slice(0,16)}/><Textarea label="Prescription notes" name="notes"/>{items.map((key,index) => <div className="medication-entry" key={key}><div className="detail-title"><h3>Medicine {index+1}</h3>{items.length>1 && <button aria-label={`Remove medicine ${index+1}`} className="text-button" type="button" onClick={() => setItems(items.filter(item => item!==key))}><Trash2 size={14}/></button>}</div><div className="substack"><Field label="Medicine name" name={`medicine_${key}`} required/><Field label="Dosage" name={`dosage_${key}`} required placeholder="Clinician-entered dosage"/><Textarea label="Instructions" name={`instructions_${key}`}/><div className="form-grid"><Field label="Total quantity" name={`quantity_${key}`} type="number" min="0.001" step="0.001" required/><Field label="Unit" name={`unit_${key}`} required placeholder="e.g. tablet, mL"/></div></div></div>)}<button className="button secondary" type="button" onClick={() => setItems([...items,crypto.randomUUID()])}><Plus size={16}/>Add medicine</button></AsyncForm></div>}
  <QueryState query={query}>{!prescriptions.length ? <Empty title="No prescriptions to show yet.">{user.role === "pharmacist" ? "Prescriptions issued for this patient will appear here." : "Prescriptions issued by an approved doctor will appear here."}</Empty> : prescriptions.map(prescription => <div className="list-row" key={prescription.id}><span className="row-icon"><FileText size={17}/></span><div className="row-content"><h3>{user.role === "pharmacist" ? prescription.patient.name : `Dr. ${prescription.doctor_name}`}</h3><p>{date(prescription.created_at)} · {prescription.items.length} medicine{prescription.items.length!==1?"s":""}</p><button className="text-button" onClick={() => setSelected(prescription.id)}>View prescription</button></div><Badge>{prescription.status}</Badge></div>)}</QueryState><Pagination page={page} setPage={setPage} length={prescriptions.length}/></Panel>;
}
export function DispensingHistory({ path, showHeading = true }: {path: string; showHeading?: boolean}) {
  const [page,setPage] = useState(1); const query = useQuery<{results: Dispensing[]}>(`${path}?page=${page}`); const events = list(query.data);
  return <Panel title={showHeading ? "Medicine handovers" : undefined} action={<Refresh onClick={query.reload}/>}><QueryState query={query}>{events.length ? events.map(event => <div className="list-row" key={event.id}><div className="row-content"><h3>{event.shop_name || event.pharmacist_name}</h3><p>{event.patient_name} · {event.patient_health_id}</p><p>{dateTime(event.created_at)} · {event.pharmacist_name}</p><p>{event.items.map(item => `${item.medicine}: ${item.quantity} ${item.unit}`).join(" · ")}</p></div><Badge>recorded</Badge></div>) : <Empty title="No medicines dispensed yet.">Confirmed handovers from verified pharmacies will be listed here.</Empty>}</QueryState><Pagination page={page} setPage={setPage} length={events.length}/></Panel>;
}
export function AuditHistory({ path, showHeading = true }: {path: string; showHeading?: boolean}) {
  const [page,setPage] = useState(1); const query = useQuery<{results: Audit[]}>(`${path}?page=${page}`); const events = list(query.data);
  return <Panel title={showHeading ? "Activity log" : undefined} action={<Refresh onClick={query.reload}/>}><div className="security-hint" style={{marginBottom:20}}><ShieldCheck size={17}/><span>Access and changes are recorded with the actor and time. This log cannot be edited from the application.</span></div><QueryState query={query}>{events.length ? <div className="table-wrap"><table><thead><tr><th>Activity</th><th>Who</th><th>When</th><th>Outcome</th></tr></thead><tbody>{events.map(event => <tr key={event.id}><td>{event.event.replaceAll("_"," ").replaceAll("."," · ")}<small>Reference: {event.request_id}</small></td><td>{event.actor_name || "System"}</td><td>{dateTime(event.created_at)}</td><td><Badge>{event.outcome}</Badge></td></tr>)}</tbody></table></div> : <Empty title="No activity to show yet.">Access to your information and important changes will appear here.</Empty>}</QueryState><Pagination page={page} setPage={setPage} length={events.length}/></Panel>;
}
